Repository Omikhleia/markdown.sile, pull requests merged in 2023-09, with the labels that each got.

#94 Small fixes
  inputters/djot.lua
  inputters/markdown.lua
  inputters/pandocast.lua
  packages/markdown/commands.lua
  packages/markdown/utils.lua
Labels: bug

#93 feat: Djot extension for symbol-based conditionals
  examples/sile-and-djot.dj
  examples/sile-and-markdown-manual-styles.yml
  examples/sile-and-markdown.md
  inputters/djot.lua
  lua-libraries/djot/attributes.lua
Labels: enhancement

#95 Allow all 'couyards' pendants in Djot (passing attributes)
  examples/sile-and-djot.dj
  packages/markdown/commands.lua
Labels: enhancement

#96 feat: improve resilient class detection
  packages/markdown/commands.lua
Labels: enhancement

#97 docs: Switch to master document with covers
  README.md
  examples/cover-back-markdown.jpg
  examples/cover-front-markdown.jpg
  examples/sile-and-markdown-backcover.dj
  examples/sile-and-markdown-bonus.sil
  examples/sile-and-markdown-manual-styles.yml
  examples/sile-and-markdown-manual.silm
  examples/toc.dj
Labels: documentation

#100 feat: Support class or package provided definition environment
  examples/sile-and-djot.dj
  examples/sile-and-markdown-backcover.dj
  examples/sile-and-markdown-manual-styles.yml
  examples/sile-and-markdown.md
  inputters/djot.lua
  inputters/markdown.lua
  inputters/pandocast.lua
  packages/markdown/commands.lua
Labels: enhancement
